export const data = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    cuisine: "Italian",
    ingredients: [
      "spaghetti",
      "tomato sauce",
      "garlic",
      "olive oil",
      "parmesan cheese",
    ],
    instructions: [
      "1. Cook spaghetti according to package instructions.",
      "2. In a separate pan, heat olive oil and sauté minced garlic until fragrant.",
      "3. Add tomato sauce to the pan and simmer for 10 minutes. \n4. Drain cooked spaghetti and toss it with the sauce. \n5. Serve hot, sprinkled with grated parmesan cheese.",
    ],
    imgUrl: "https://source.unsplash.com/random",
  },
  {
    id: 2,
    name: "Tacos",
    cuisine: "Mexican",
    ingredients: [
      "tortillas",
      "ground beef",
      "onion",
      "bell pepper",
      "salsa",
      "shredded cheese",
    ],
    instructions: [
      "1. In a skillet, cook ground beef with diced onion and bell pepper until browned.",
      "2. Warm tortillas in a separate pan.",
      "3. Spoon the cooked beef mixture onto the tortillas.",
      "4. Top with salsa and shredded cheese.",
    ],
    imgUrl: "https://source.unsplash.com/random",
  },
  {
    id: 3,
    name: "Chicken Tikka Masala",
    cuisine: "Indian",
    ingredients: [
      "chicken",
      "yogurt",
      "ginger",
      "garlic",
      "garam masala",
      "turmeric",
      "cumin",
      "chili powder",
    ],
    instructions: [
      "1. In a bowl, mix yogurt, ginger, garlic, garam masala, turmeric, cumin, and chili powder to make a marinade.",
      "2. Add chicken pieces to the marinade and let it sit for at least 1 hour.",
      "3. Preheat the oven to 375°F (190°C).",
      "4. Place marinated chicken on a baking sheet and bake for 25-30 minutes until cooked through. \n5. Serve hot with rice or naan bread.",
    ],
    imgUrl: "https://source.unsplash.com/random",
  },
  {
    id: 4,
    name: "Pad Thai",
    cuisine: "Thai",
    ingredients: [
      "rice noodles",
      "chicken",
      "bell peppers",
      "carrots",
      "soy sauce",
      "lime juice",
      "peanuts",
      "cilantro",
    ],
    instructions: [
      "1. Cook rice noodles according to package instructions and set aside.",
      "2. In a pan, cook chicken with sliced bell peppers and julienned carrots until cooked through.",
      "3. In a small bowl, whisk together soy sauce and lime juice to make the sauce.",
      "4. Add the cooked noodles to the pan with the chicken and vegetables, then pour the sauce over them.",
      "5. Toss everything together and garnish with crushed peanuts and fresh cilantro.",
    ],
    imgUrl: "https://source.unsplash.com/random",
  },
];
